version = "2"

[linters]
default = "none"
enable = [
  "errcheck",
  "gocyclo",
  "govet",
  "ineffassign",
  "staticcheck",
  "unused"
]

[linters.settings.gocyclo]
min-complexity = 15

[linters.settings.govet]
enable-all = true
disable = [
  "fieldalignment"
]

[linters.exclusions]
generated = "lax"
presets = [
  "comments",
  "common-false-positives",
  "legacy",
  "std-error-handling"
]
paths = [
  "third_party$",
  "builtin$",
  "examples$"
]

[formatters]
enable = [
  "gofmt"
]

[formatters.exclusions]
generated = "lax"
paths = [
  "third_party$",
  "builtin$",
  "examples$"
]
