repos:
  - repo: local
    hooks:
      - id: docgen
        name: Update Cobra CLI documentation
        entry: go run ./internal/tools/docgen -out ./docs/cli -format markdown
        language: system
        pass_filenames: false
